# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SearchSnos
                                 A QGIS plugin
 Поиск сносимых домов при выделении стартовой площадки
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Антон
        email                : a.khalluk@dev-city.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .search_snos_dialog import SearchSnosDialog
import os.path


class SearchSnos:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SearchSnos_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Поиск сносимых домов')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SearchSnos', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Создание кнопки на панели инструментов"""
        import os
        from qgis.PyQt.QtGui import QIcon
        from qgis.PyQt.QtWidgets import QAction

        # Путь к вашей новой иконке в папке плагина
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        
        # Создаем действие (кнопку), указывая прямой путь к файлу
        self.action = QAction(
            QIcon(icon_path), 
            u'Поиск сносимых домов', 
            self.iface.mainWindow()
        )
        
        # Подключаем запуск метода run
        self.action.triggered.connect(self.run)

        # Добавляем на панель и в меню
        self.iface.addToolBarIcon(self.action)
        self.iface.addPluginToVectorMenu(u'Поиск сносимых домов', self.action)
        
        # Сохраняем в список действий (нужно для корректного удаления при выключении)
        self.actions.append(self.action)


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Поиск сносимых домов'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Метод, который запускается при клике на иконку плагина"""
        from qgis.core import (QgsProject, QgsFeature, QgsGeometry, QgsVectorLayer, 
                               QgsField, QgsExpression, QgsFeatureRequest, QgsPointXY,
                               QgsSingleSymbolRenderer, QgsSimpleLineSymbolLayer, QgsSymbol,
                               QgsPalLayerSettings, QgsTextFormat, QgsTextBufferSettings,
                               QgsVectorLayerSimpleLabeling, QgsMarkerSymbol)
        from qgis.PyQt.QtCore import QVariant, Qt
        from qgis.PyQt.QtWidgets import QMessageBox, QInputDialog
        from qgis.PyQt.QtGui import QColor

        # 1. Инициализация проекта и поиск слоев
        root = QgsProject.instance()
        layers_a = root.mapLayersByName('start_plot')
        layers_b = root.mapLayersByName('snos')

        if not layers_a or not layers_b:
            QMessageBox.critical(self.iface.mainWindow(), "Ошибка", "Слои 'start_plot' и 'snos' не найдены!")
            return

        layer_A = layers_a[0]
        layer_B = layers_b[0]

        # 2. Определение площадки
        selected_A = layer_A.selectedFeatures()
        id_field = next((f for f in layer_A.fields().names() if f.upper() == 'ID'), None)
        
        if not id_field:
            QMessageBox.critical(self.iface.mainWindow(), "Ошибка", "В слое площадок нет поля ID!")
            return

        main_feat = None
        if selected_A:
            main_feat = selected_A[0]
        else:
            input_id, ok = QInputDialog.getText(self.iface.mainWindow(), 
                                               "Стартовая площадка", 
                                               "Введите ID стартовой площадки:")
            if not ok or not input_id: 
                layer_A.removeSelection()
                return 

            is_string = layer_A.fields().field(id_field).type() == QVariant.String
            val_find = f"'{input_id}'" if is_string else str(input_id)
            
            request_A = QgsFeatureRequest().setFilterExpression(f'"{id_field}" = {val_find}')
            features_A = list(layer_A.getFeatures(request_A))
            
            if not features_A:
                QMessageBox.warning(self.iface.mainWindow(), "Не найдено", f"Площадка с ID {input_id} не найдена.")
                layer_A.removeSelection()
                layer_B.removeSelection()
                return
            
            main_feat = features_A[0]
            layer_A.selectByIds([main_feat.id()])

        target_id = main_feat[id_field]
        plot_address = main_feat['adress'] if 'adress' in [f.name() for f in layer_A.fields()] else "Адрес не указан"

        # 3. ПОИСК СВЯЗАННЫХ ДОМОВ
        id_fields_B = []
        for join in layer_B.vectorJoins():
            join_layer = join.joinLayer()
            if join_layer and join_layer.fields().count() > 3:
                orig_name = join_layer.fields().at(3).name()
                full_name = join.prefix() + orig_name
                if layer_B.fields().indexFromName(full_name) != -1:
                    id_fields_B.append(full_name)

        found_houses = []
        if id_fields_B:
            val_str = f"'{target_id}'" if isinstance(target_id, str) else str(target_id)
            expr = " OR ".join([f'"{f}" = {val_str}' for f in id_fields_B])
            found_houses = list(layer_B.getFeatures(QgsFeatureRequest().setFilterExpression(expr)))
        
        if not found_houses:
            QMessageBox.information(self.iface.mainWindow(), "Результат поиска", 
                                    f"В площадку ID {target_id} не переселяются сносимые дома.")
            layer_A.removeSelection()
            layer_B.removeSelection()
            return
        
        # УДАЛЕНИЕ СТАРЫХ СЛОЕВ
        layers_to_remove = [l.id() for l in root.mapLayers().values() if l.name().endswith("_связи") or l.name().endswith("_центроиды")]
        if layers_to_remove:
            root.removeMapLayers(layers_to_remove)
        
        # 4. СОЗДАНИЕ СЛОЕВ
        crs = layer_A.crs().authid()
        line_layer = QgsVectorLayer(f"LineString?crs={crs}", f"{target_id}_связи", "memory")
        point_layer = QgsVectorLayer(f"Point?crs={crs}", f"{target_id}_центроиды", "memory") # Переименовано
        
        line_prov = line_layer.dataProvider()
        point_prov = point_layer.dataProvider()
        
        # --- ПОЛЯ ДЛЯ ЛИНЕЙНОГО СЛОЯ ---
        line_fields = [
            QgsField("ADRESS_START", QVariant.String), 
            QgsField("DISTANCE", QVariant.Double, "Double", 10, 2)
        ]
        added_line = {"ADRESS_START", "DISTANCE"}
        for f in layer_B.fields():
            if f.name() not in added_line:
                line_fields.append(f)
        
        line_prov.addAttributes(line_fields)
        line_layer.updateFields()

        # --- ПОЛЯ ДЛЯ ТОЧЕЧНОГО СЛОЯ ---
        point_fields = [
            QgsField("OBJECT_TYPE", QVariant.String),
            QgsField("DISTANCE", QVariant.Double, "Double", 10, 2)
        ]
        added_point = {"OBJECT_TYPE", "DISTANCE"}
        
        # Добавляем поля от start_plot
        for f in layer_A.fields():
            if f.name() not in added_point:
                point_fields.append(f)
                added_point.add(f.name())
        
        # Добавляем поля от snos
        for f in layer_B.fields():
            if f.name() not in added_point:
                point_fields.append(f)
                added_point.add(f.name())

        point_prov.addAttributes(point_fields)
        point_layer.updateFields()

        # Геометрия старта
        geom_A = main_feat.geometry()
        start_geom = geom_A.centroid() if geom_A.contains(geom_A.centroid()) else geom_A.pointOnSurface()
        start_pt = start_geom.asPoint()

        new_lines = []
        new_points = []

        # 4.1 ТОЧКА ЦЕНТРА ПЛОЩАДКИ
        feat_start_point = QgsFeature(point_layer.fields())
        feat_start_point.setGeometry(start_geom)
        feat_start_point.setAttribute("OBJECT_TYPE", "Стартовая площадка")
        feat_start_point.setAttribute("DISTANCE", 0)
        for f in layer_A.fields():
            feat_start_point.setAttribute(f.name(), main_feat[f.name()])
        new_points.append(feat_start_point)

        # 4.2 ДОМА (ЛИНИИ И ТОЧКИ)
        for house in found_houses:
            h_geom = house.geometry()
            h_center = h_geom.centroid() if h_geom.contains(h_geom.centroid()) else h_geom.pointOnSurface()
            line_geom = QgsGeometry.fromPolylineXY([start_pt, h_center.asPoint()])
            dist = round(line_geom.length(), 2)
            
            # Создание линии
            f_line = QgsFeature(line_layer.fields())
            f_line.setGeometry(line_geom)
            f_line.setAttribute("ADRESS_START", plot_address)
            f_line.setAttribute("DISTANCE", dist)
            for f in layer_B.fields(): 
                f_line.setAttribute(f.name(), house[f.name()])
            new_lines.append(f_line)
            
            # Создание точки дома
            f_point = QgsFeature(point_layer.fields())
            f_point.setGeometry(h_center)
            f_point.setAttribute("OBJECT_TYPE", "Сносимый дом")
            f_point.setAttribute("DISTANCE", dist)
            for f in layer_B.fields(): 
                f_point.setAttribute(f.name(), house[f.name()])
            new_points.append(f_point)

        line_prov.addFeatures(new_lines)
        point_prov.addFeatures(new_points)

        # 5. СТИЛИЗАЦИЯ
        from qgis.core import (QgsSingleSymbolRenderer, QgsRuleBasedRenderer, 
                               QgsSymbol, QgsSimpleLineSymbolLayer, QgsMarkerSymbol)

        # 5.1 Стиль для ЛИНЕЙНОГО слоя
        symbol_line = QgsSymbol.defaultSymbol(line_layer.geometryType())
        line_layer_style = QgsSimpleLineSymbolLayer.create({
            'color': 'red', 
            'width': '0.4', 
            'line_style': 'solid'
        })
        symbol_line.changeSymbolLayer(0, line_layer_style)
        line_layer.setRenderer(QgsSingleSymbolRenderer(symbol_line))

        # 5.2 Стиль для ТОЧЕЧНОГО слоя
        # Создаем пустой корень правил
        root_rule = QgsRuleBasedRenderer.Rule(None)

        # Правило для Стартовой площадки (Синяя точка, покрупнее)
        symbol_start = QgsMarkerSymbol.createSimple({
            'name': 'circle',
            'color': 'blue',
            'outline_color': 'white',
            'size': '4',
            'outline_width': '0.4'
        })
        rule_start = QgsRuleBasedRenderer.Rule(symbol_start, 
                                               filterExp="\"OBJECT_TYPE\" = 'Стартовая площадка'", 
                                               label="Стартовая площадка")

        # Правило для Сносимых домов (Красная точка, поменьше)
        symbol_house = QgsMarkerSymbol.createSimple({
            'name': 'circle',
            'color': 'red',
            'outline_color': 'white',
            'size': '2.5',
            'outline_width': '0.3'
        })
        rule_house = QgsRuleBasedRenderer.Rule(symbol_house, 
                                               filterExp="\"OBJECT_TYPE\" = 'Сносимый дом'", 
                                               label="Сносимые дома")

        # Добавляем правила в дерево и применяем к слою
        root_rule.appendChild(rule_start)
        root_rule.appendChild(rule_house)
        
        point_renderer = QgsRuleBasedRenderer(root_rule)
        point_layer.setRenderer(point_renderer)

        # Обновляем интерфейс
        line_layer.triggerRepaint()
        point_layer.triggerRepaint()

        # 6. ПОДПИСИ (для линий)
        text_format = QgsTextFormat()
        text_format.setSize(8)
        text_format.setColor(QColor("black"))
        buffer = QgsTextBufferSettings()
        buffer.setEnabled(True)
        buffer.setSize(0.8)
        buffer.setColor(QColor("white"))
        text_format.setBuffer(buffer)

        label_settings = QgsPalLayerSettings()
        label_settings.setFormat(text_format)
        label_settings.isExpression = True
        label_settings.fieldName = "format_number(DISTANCE, 0) || ' м'"
        label_settings.enabled = True
        label_settings.placement = QgsPalLayerSettings.Line 
        label_settings.placementFlags = QgsPalLayerSettings.OnLine | QgsPalLayerSettings.MapOrientation
        
        line_layer.setLabeling(QgsVectorLayerSimpleLabeling(label_settings))
        line_layer.setLabelsEnabled(True)

        # 7. ДОБАВЛЕНИЕ В ПРОЕКТ
        root.addMapLayer(line_layer)
        root.addMapLayer(point_layer)
        
        # Упорядочивание слоев в дереве
        layer_tree = root.layerTreeRoot()
        snos_node = layer_tree.findLayer(layer_B.id())
        
        for lyr in [point_layer, line_layer]:
            node = layer_tree.findLayer(lyr.id())
            if snos_node and node:
                parent = snos_node.parent()
                idx = parent.children().index(snos_node)
                parent.insertChildNode(idx, node.clone())
                parent.removeChildNode(node)

        self.iface.mapCanvas().refresh()

        # ЗУМ И ВЫДЕЛЕНИЕ
        full_extent = main_feat.geometry().boundingBox()
        for h in found_houses: full_extent.combineExtentWith(h.geometry().boundingBox())
        full_extent.grow(full_extent.width() * 0.15)
        self.iface.mapCanvas().setExtent(full_extent)
        
        layer_A.selectByIds([main_feat.id()])
        layer_B.selectByIds([f.id() for f in found_houses])
        self.iface.setActiveLayer(layer_A)
