# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SearchSnos
                                 A QGIS plugin
 Поиск сносимых домов при выделении стартовой площадки
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Антон
        email                : a.khalluk@dev-city.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .search_snos_dialog import SearchSnosDialog
import os.path


class SearchSnos:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SearchSnos_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Поиск сносимых домов')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SearchSnos', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Создание кнопки на панели инструментов"""
        import os
        from qgis.PyQt.QtGui import QIcon
        from qgis.PyQt.QtWidgets import QAction

        # Путь к вашей новой иконке в папке плагина
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        
        # Создаем действие (кнопку), указывая прямой путь к файлу
        self.action = QAction(
            QIcon(icon_path), 
            u'Поиск сносимых домов при выделении стартовой площадки', 
            self.iface.mainWindow()
        )
        
        # Подключаем запуск метода run
        self.action.triggered.connect(self.run)

        # Добавляем на панель и в меню
        self.iface.addToolBarIcon(self.action)
        self.iface.addPluginToVectorMenu(u'Поиск сносимых домов', self.action)
        
        # Сохраняем в список действий (нужно для корректного удаления при выключении)
        self.actions.append(self.action)


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Поиск сносимых домов'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Метод, который запускается при клике на иконку плагина"""
        from qgis.core import (QgsProject, QgsFeature, QgsGeometry, QgsVectorLayer, 
                               QgsField, QgsExpression, QgsFeatureRequest)
        from qgis.PyQt.QtCore import QVariant
        from qgis.PyQt.QtWidgets import QMessageBox, QInputDialog

        # 1. Инициализация проекта и поиск слоев
        root = QgsProject.instance()
        layers_a = root.mapLayersByName('start_plot')
        layers_b = root.mapLayersByName('snos')

        if not layers_a or not layers_b:
            QMessageBox.critical(self.iface.mainWindow(), "Ошибка", "Слои 'start_plot' и 'snos' не найдены!")
            return

        layer_A = layers_a[0]
        layer_B = layers_b[0]

        # 2. Определение площадки
        selected_A = layer_A.selectedFeatures()
        id_field = next((f for f in layer_A.fields().names() if f.upper() == 'ID'), None)
        
        if not id_field:
            QMessageBox.critical(self.iface.mainWindow(), "Ошибка", "В слое площадок нет поля ID!")
            return

        main_feat = None
        if selected_A:
            main_feat = selected_A[0]
        else:
            input_id, ok = QInputDialog.getText(self.iface.mainWindow(), 
                                               "Стартовая площадка", 
                                               "Введите ID стартовой площадки:")
            if not ok or not input_id:
                return 

            is_string = layer_A.fields().field(id_field).type() == QVariant.String
            val_find = f"'{input_id}'" if is_string else str(input_id)
            
            request_A = QgsFeatureRequest().setFilterExpression(f'"{id_field}" = {val_find}')
            features_A = list(layer_A.getFeatures(request_A))
            
            if not features_A:
                QMessageBox.warning(self.iface.mainWindow(), "Не найдено", f"Площадка с ID {input_id} не найдена.")
                return
            
            main_feat = features_A[0]
            layer_A.selectByIds([main_feat.id()])

        target_id = main_feat[id_field]

        # 3. ПОИСК СВЯЗАННЫХ ДОМОВ (ЛОГИКА ПО ИНДЕКСУ СТОЛБЦА №4)
        # Ищем во всех Joins поле, которое в исходном Excel имело индекс 3
        id_fields_B = []
        for join in layer_B.vectorJoins():
            join_layer = join.joinLayer()
            if join_layer and join_layer.fields().count() > 3:
                # Получаем имя 4-го столбца (индекс 3) из таблицы Excel
                orig_name = join_layer.fields().at(3).name()
                # Формируем имя поля, как оно выглядит в слое 'snos' (Префикс_Имя)
                full_name = join.prefix() + orig_name
                if layer_B.fields().indexFromName(full_name) != -1:
                    id_fields_B.append(full_name)

        found_houses = []
        if id_fields_B:
            val_str = f"'{target_id}'" if isinstance(target_id, str) else str(target_id)
            expr = " OR ".join([f'"{f}" = {val_str}' for f in id_fields_B])
            found_houses = list(layer_B.getFeatures(QgsFeatureRequest().setFilterExpression(expr)))
        
        if not found_houses:
            QMessageBox.information(self.iface.mainWindow(), "Результат поиска", 
                                    f"В площадку ID {target_id} не переселяются сносимые дома.")
            layer_B.removeSelection()
            return 
        
        # Выделение и Зум
        ids_B = [f.id() for f in found_houses]
        layer_B.selectByIds(ids_B)
        
        full_extent = main_feat.geometry().boundingBox()
        for house in found_houses:
            full_extent.combineExtentWith(house.geometry().boundingBox()) 
        
        padding = max(full_extent.width(), full_extent.height()) * 0.15
        full_extent.grow(padding if padding > 0 else 100)
        self.iface.mapCanvas().setExtent(full_extent)
        self.iface.mapCanvas().refresh()

        # 4. СОЗДАНИЕ СЛОЯ С ЦЕНТРОИДАМИ
        crs = layer_A.crs().authid()
        centroid_layer = QgsVectorLayer(f"Point?crs={crs}", f"{target_id}_центроиды", "memory")
        prov = centroid_layer.dataProvider()
        
        all_fields = [QgsField("OBJECT_TYPE", QVariant.String)]
        added_names = {"OBJECT_TYPE"}

        for f in list(layer_A.fields()) + list(layer_B.fields()):
            if f.name() not in added_names:
                all_fields.append(f)
                added_names.add(f.name())

        prov.addAttributes(all_fields)
        centroid_layer.updateFields()
        new_fields = centroid_layer.fields()

        # Добавляем центроид площадки
        feat_A = QgsFeature(new_fields)
        feat_A.setGeometry(main_feat.geometry().centroid())
        feat_A.setAttribute("OBJECT_TYPE", "Стартовая площадка")
        for f in layer_A.fields():
            feat_A.setAttribute(f.name(), main_feat[f.name()])
        prov.addFeature(feat_A)

        # Добавляем центроиды домов
        for house in found_houses:
            feat_B = QgsFeature(new_fields)
            feat_B.setGeometry(house.geometry().centroid())
            feat_B.setAttribute("OBJECT_TYPE", "Сносимый дом")
            for f in layer_B.fields():
                feat_B.setAttribute(f.name(), house[f.name()])
            prov.addFeature(feat_B)

        # 5. Добавление в проект и управление деревом слоев
        root.addMapLayer(centroid_layer)
        layer_tree = root.layerTreeRoot()
        snos_node = layer_tree.findLayer(layer_B.id())
        new_node = layer_tree.findLayer(centroid_layer.id())
        
        if snos_node and new_node:
            parent = snos_node.parent()
            index = parent.children().index(snos_node)
            new_clone = new_node.clone()
            parent.insertChildNode(index, new_clone)
            parent.removeChildNode(new_node)

        layer_A.selectByIds([main_feat.id()])
